### PR TITLE
Hide message in stdout if SCCcredentials is missing (bsc#1222277)

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

Hide message in stdout if SCCcredentials is missing (bsc#1222277)

## Test coverage
- No tests
- [x] **DONE**

## Links

Issue(s): #

- [ ] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by aaannz — APPROVED** [review]
LGTM.

I wonder if it's possible to avoid using `|| true` and instead have inspectdata contain if it's mandatory or optional instpectdata.

**Comment by mbussolotto** [comment]
> I wonder if it's possible to avoid using || true and instead have inspectdata contain if it's mandatory or optional instpectdata.

We can put `|| true` directly  in the template https://github.com/uyuni-project/uyuni-tools/blob/fe5677afb0205c2ea4c7ca1fcd125f1b7de26809/mgradm/shared/templates/inspectTemplate.go#L17 and add the some logic for mandatory and optional data. But I'm not sure what we would like to do if a mandatory data is missing ....I think we should not stop the program but just log an error (or warning?) message, right?

**Comment by avshiliaev** [comment]
The link to BZ for convenience :smiley: 
https://bugzilla.suse.com/show_bug.cgi?id=1222277

**Review by cbosdo — APPROVED** [review]

**Review by Bischoff — APPROVED** [review]
thanks!

**Pull request merged**
