### PR TITLE
Fixes pulling of coco or hub images if replicas count is set in config file

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

Completes the detection of the changed values of `--coco-replicas` and `--hubxmlrpc-replicas` parameters by checking the configuration and environment variable changes too.

This PR also adds unit tests of the parsing of all the parameters and fixes the `--cacert` parsing uncovered then.

## Test coverage
- Unit tests were added

- [X] **DONE**

## Links

Issue(s): https://github.com/SUSE/spacewalk/issues/25072

- [X] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by aaannz — APPROVED** [review]
LGTM, just question. Why are some of the flags tests part of test_utils and not next to their commands?

**Comment by cbosdo** [comment]
> LGTM, just question. Why are some of the flags tests part of test_utils and not next to their commands?

In theory they should all be in `test_utils` to not confuse them with real code... If there are some outside and not in a `_test.go` file then that's a forgotten bit.

**Comment by aaannz** [comment]
> > LGTM, just question. Why are some of the flags tests part of test_utils and not next to their commands?
> 
> In theory they should all be in `test_utils` to not confuse them with real code... If there are some outside and not in a `_test.go` file then that's a forgotten bit.

By next to their commands I meant of course in separate _test.go, like there for `distro.go`, they are tested in `distro_test.go`.
I was wondering why there is `shared/test_utils/flags_tests/api.go` and not `mgrctl/api/api_test.go`. Is it because APIFlags are shared and can be added to multiple commands?

Similarly for mgradm_install, mgrpxy_kubernetes, etc.

**Comment by cbosdo** [comment]
> > > LGTM, just question. Why are some of the flags tests part of test_utils and not next to their commands?
> > 
> > 
> > In theory they should all be in `test_utils` to not confuse them with real code... If there are some outside and not in a `_test.go` file then that's a forgotten bit.
> 
> By next to their commands I meant of course in separate _test.go, like there for `distro.go`, they are tested in `distro_test.go`. I was wondering why there is `shared/test_utils/flags_tests/api.go` and not `mgrctl/api/api_test.go`. Is it because APIFlags are shared and can be added to multiple commands?
> 
> Similarly for mgradm_install, mgrpxy_kubernetes, etc.

Yes, those are shared flags... and it's easy to fall into import cycles.

**Comment by szachovy** [comment]
## Combination 1: replicas in config file (DONE)

Having no images:
```
wiktor-srv:~/uyuni-tools # podman image ls
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
```

Having `config.yaml` file:
```
registry: registry.suse.com
image: registry.suse.com/suse/manager/5.0/x86_64/server
scc:
  user: <redacted manually>
  password: <redacted manually>
coco:
  image: registry.suse.com/suse/manager/5.0/x86_64/server-attestation
  replicas: 1
hubxmlrpc:
  image: registry.suse.com/suse/manager/5.0/x86_64/server-hub-xmlrpc-api
tag: 5.0.1
```

Using install command:
```
wiktor-srv:~/uyuni-tools # ./bin/mgradm install podman --config config.yaml --logLevel trace
```

It pulls both the images:
```
wiktor-srv:~/uyuni-tools # podman image ls
REPOSITORY                                                    TAG         IMAGE ID      CREATED      SIZE
registry.suse.com/suse/manager/5.0/x86_64/server              5.0.1       8417ea2e4cbe  3 weeks ago  2.18 GB
registry.suse.com/suse/manager/5.0/x86_64/server-attestation  5.0.1       65531bcdccd0  3 weeks ago  361 MB
```

Both containers are healthy:
```
wiktor-srv:~/uyuni-tools # podman ps
CONTAINER ID  IMAGE                                                               COMMAND               CREATED        STATUS                  PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NAMES
4a8577b21c61  registry.suse.com/suse/manager/5.0/x86_64/server:5.0.1              /usr/lib/systemd/...  5 minutes ago  Up 5 minutes (healthy)  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4505-4506->4505-4506/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5556-5557->5556-5557/tcp, 0.0.0.0:9100->9100/tcp, 0.0.0.0:9187->9187/tcp, 0.0.0.0:9800->9800/tcp, 0.0.0.0:25151->25151/tcp, 0.0.0.0:69->69/udp, :::80->80/tcp, :::443->443/tcp, :::4505-4506->4505-4506/tcp, :::5432->5432/tcp, :::5556-5557->5556-5557/tcp, :::9100->9100/tcp, :::9187->9187/tcp, :::9800->9800/tcp, :::25151->25151/tcp, :::69->69/udp  uyuni-server
8efc4a5b171e  registry.suse.com/suse/manager/5.0/x86_64/server-attestation:5.0.1  /usr/sbin/coco-at...  2 minutes ago  Up 2 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                                                                                                                                        uyuni-server-attestation-0
```

## Combination 2: replicas in CLI, the rest in config file (DONE)

Having no images:
```
wiktor-srv:~/uyuni-tools # podman image ls
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
```

Having `config.yaml` file:
```
registry: registry.suse.com
image: registry.suse.com/suse/manager/5.0/x86_64/server
scc:
  user: <redacted manually>
  password: <redacted manually>
coco:
  image: registry.suse.com/suse/manager/5.0/x86_64/server-attestation
hubxmlrpc:
  image: registry.suse.com/suse/manager/5.0/x86_64/server-hub-xmlrpc-api
tag: 5.0.1
```

Using install command:
```
wiktor-srv:~/uyuni-tools # ./bin/mgradm install podman --config config.yaml --coco-replicas 1 --logLevel trace
```

It pulls both the images:
```
wiktor-srv:~/uyuni-tools # podman image ls
REPOSITORY                                                    TAG         IMAGE ID      CREATED      SIZE
registry.suse.com/suse/manager/5.0/x86_64/server              5.0.1       8417ea2e4cbe  3 weeks ago  2.18 GB
registry.suse.com/suse/manager/5.0/x86_64/server-attestation  5.0.1       65531bcdccd0  3 weeks ago  361 MB
```

Both containers are healthy:
```
wiktor-srv:~/uyuni-tools # podman ps
CONTAINER ID  IMAGE                                                               COMMAND               CREATED        STATUS                  PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NAMES
3489714e25f6  registry.suse.com/suse/manager/5.0/x86_64/server:5.0.1              /usr/lib/systemd/...  7 minutes ago  Up 7 minutes (healthy)  0.0.0.0:69->69/udp, 0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4505-4506->4505-4506/tcp, 0.0.0.0:5432->5432/tcp, 0.0.0.0:5556-5557->5556-5557/tcp, 0.0.0.0:9100->9100/tcp, 0.0.0.0:9187->9187/tcp, 0.0.0.0:9800->9800/tcp, 0.0.0.0:25151->25151/tcp, :::80->80/tcp, :::443->443/tcp, :::4505-4506->4505-4506/tcp, :::5432->5432/tcp, :::5556-5557->5556-5557/tcp, :::9100->9100/tcp, :::9187->9187/tcp, :::9800->9800/tcp, :::25151->25151/tcp, :::69->69/udp  uyuni-server
0cec03c91816  registry.suse.com/suse/manager/5.0/x86_64/server-attestation:5.0.1  /usr/sbin/coco-at...  4 minutes ago  Up 4 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                                                                                                                                        uyuni-server-attestation-0
```

**Review by szachovy — APPROVED** [review]

**Pull request merged**
