### PR TITLE
Fix namespace usage on mgrctl cp command

### PR DESCRIPTION
**Pull request by rjpmestre**
## What does this PR change?

Fix namespace usage on mgrctl cp command

## Test coverage
- No tests: not in scope

- [x] **DONE**

## Links

Issue(s): #

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by mbussolotto — COMMENTED** [review]
I had the impression that `-n` was required by kubernetes and not by rodman...have you tested both scenario with this change?

**Comment by rjpmestre** [comment]
> I had the impression that `-n` was required by kubernetes and not by podman...have you tested both scenario with this change?

Thank you for pointing that out. I realized the tests i ran were successful because I was using default as namespace.

**Review by mbussolotto — APPROVED** [review]
PR approved, but please re-test `mgradm install podman` and `mgradm install kubernetes` with this change. And remember to backport it to 5.0, thanks!

**Comment by deneb-alpha** [comment]
> PR approved, but please re-test `mgradm install podman` and `mgradm install kubernetes` with this change. And remember to backport it to 5.0, thanks!

please do NOT backport. the previous PR has been merged only in master

**Comment by cbosdo** [comment]
> > PR approved, but please re-test `mgradm install podman` and `mgradm install kubernetes` with this change. And remember to backport it to 5.0, thanks!
> 
> please do NOT backport. the previous PR has been merged only in master

I fear we'll need to backport the namespace fixing PR since that also affects the proxy and will be annoying for backporting other PRs.

**Comment by aaannz** [comment]
We need a backport here. 5.0 branch has this problem too, see https://github.com/SUSE/uyuni-tools/blob/Manager-5.0/shared/connection.go#L346

**Comment by aaannz** [comment]
Backport PR https://github.com/SUSE/uyuni-tools/pull/26

**Pull request merged**
