### PR TITLE
change security-opts values to use = instead of :

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

see title

## Test coverage
- No tests

- [ ] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni/issues/8869

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]

**Comment by mbussolotto** [comment]
@admd @deneb-alpha @raulillo82 looks like a problem for `mgradm migrate` and `mgradm upgrade` on Ubuntu 22.04, but maybe it might happens also in system when a new podman version will be released...not sure if it's something you want to merge soon, what do you think?

**Comment by deneb-alpha** [comment]
> Ubuntu 22.04

it seems they  have version 3.4.4 according to:
https://packages.ubuntu.com/search?suite=jammy-updates&searchon=names&keywords=podman

and we require version 4.5.0 according to https://github.com/uyuni-project/uyuni-tools/blob/main/uyuni-tools.spec#L102  :thinking:

**Comment by cbosdo** [comment]
> > Ubuntu 22.04
> 
> it seems they have version 3.4.4 according to: https://packages.ubuntu.com/search?suite=jammy-updates&searchon=names&keywords=podman
> 
> and we require version 4.5.0 according to https://github.com/uyuni-project/uyuni-tools/blob/main/uyuni-tools.spec#L102 🤔

Indeed I would rule that change out. That means the minimum Ubuntu version to run the server is Noble (24.04)

**Review by rjmateus — APPROVED** [review]
lgtm

**Pull request merged**
